services:
  Athena:
    environment:
      - DISPLAY=novnc:0.0 
      - UDEV=on
    image: mcgillrobotics/humanoid:latest
    volumes:
      # - /dev:/dev  # uncomment when using real servos
      - ./:/root/Humanoid
    # privileged: true  # uncomment when using real servos
    command: bash -c "chmod -R +x /root/Humanoid/catkin_ws/src && tail -f /dev/null"
    ports:
      - "10000:10000"
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # novnc:
  #   image: theasp/novnc:latest
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - RUN_XTERM=no
  #     - DISPLAY_WIDTH=6000
  #     - DISPLAY_HEIGHT=3000 #need to adjust based off height and width of your screen, going for bigger values is typically recommended.