services:
  athena:
    build: .
    volumes:
      - ./:/root/Humanoid
    command: bash -c "tail -f /dev/null"
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
