# Each joint motor has a float32 array with their feedback values
# Each array has 3 values in this order: [position, velocity, load]
float32[] right_shoulder_pitch_fb
float32[] right_shoulder_roll_fb
float32[] right_elbow_fb
float32[] left_shoulder_pitch_fb
float32[] left_shoulder_roll_fb
float32[] left_elbow_fb
float32[] left_hip_roll_fb
float32[] left_hip_pitch_fb
float32[] left_knee_fb
float32[] right_hip_roll_fb
float32[] right_hip_pitch_fb
float32[] right_knee_fb
