# Each joint motor has a float32 array with their feedback values
# Each array has 3 values in this order: [position, velocity, load]
float32[] right_shoulder_pitch
float32[] right_shoulder_roll
float32[] right_elbow
float32[] left_shoulder_pitch
float32[] left_shoulder_roll
float32[] left_elbow
float32[] left_hip_roll
float32[] left_hip_pitch
float32[] left_knee
float32[] right_hip_roll
float32[] right_hip_pitch
float32[] right_knee
